import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    contentContainer: {
        paddingHorizontal: 16,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 12,
        fontFamily: 'Wellfleet',
        fontSize: 16,
        color: '#555',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        marginBottom: 0,
    },
    backButton: {
        padding: 8,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#000',
        fontFamily: 'Wellfleet',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    title: {
        fontSize: 24,
        color: '#333',
        marginBottom: 10,
        textAlign: 'center',
        fontFamily: 'Wellfleet',
    },
    formGroup: {
        marginBottom: 5,
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
        fontFamily: 'Wellfleet',
    },
    input: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 10,
        fontSize: 13,
        color: '#333',
        borderWidth: 1,
        borderColor: '#e1e1e1',
        fontFamily: 'Wellfleet',
        textAlign: "justify"
    },
    pickerContainer: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e1e1e1',
        overflow: 'hidden',
        fontFamily: 'Wellfleet',
    },
    picker: {
        height: 50,
        fontFamily: 'Wellfleet',
    },
    webPicker: {
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    priceContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 5,
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
    },
    priceLabel: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        fontFamily: 'Wellfleet',
    },
    priceValue: {
        fontSize: 24,
        color: '#4A90E2',
        fontFamily: 'Wellfleet',
    },
    submitButton: {
        backgroundColor: '#4A90E2',
        borderRadius: 8,
        padding: 16,
        alignItems: 'center',
        marginTop: 8,
    },
    submitButtonDisabled: {
        backgroundColor: '#ccc',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
        fontFamily: 'Wellfleet',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.95)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 24,
        width: '100%',
        maxWidth: 400,
    },
    modalHeader: {
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        fontSize: 24,
        color: '#333',
        marginTop: 12,
        fontFamily: 'Wellfleet',
    },
    modalBody: {
        marginBottom: 24,
    },
    modalText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 24,
        fontFamily: 'Wellfleet',
    },
    orderDetails: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 16,
    },
    orderItem: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        marginBottom: 12,
    },
    orderItemv: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    orderLabel: {
        fontSize: 16,
        color: '#666',
        fontFamily: 'Wellfleet',
    },
    orderValue: {
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
        fontFamily: 'Wellfleet',
        marginHorizontal: 5,
    },
    orderValueD: {
        fontSize: 14,
        color: '#333',
        fontFamily: 'Wellfleet',
        marginRight: 60,
        marginLeft: 10,
        textAlign: "justify",
    },
    totalItem: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#e1e1e1',
    },
    totalLabel: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        fontFamily: 'Wellfleet',
    },
    modalTotalPrice: {
        fontSize: 24,
        color: '#4A90E2',
        fontFamily: 'Wellfleet',
    },
    finalizeButton: {
        backgroundColor: '#4A90E2',
        borderRadius: 8,
        padding: 16,
        alignItems: 'center',
    },
    finalizeButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
        fontFamily: 'Wellfleet',
    },
    modalBackButton: {
        marginBottom: 10,
    },
    contador: {
        marginTop: 5,
        fontSize: 14,
        color: '#666',
        alignSelf: 'flex-end',
    },
});
